name: erp_scale_sim_app
description: Flutter Web app shell for erp_scale_sim reproduction.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  erp_scale_sim:
    path: ../
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  module_01:
    path: ../packages/module_01
  module_02:
    path: ../packages/module_02
  module_03:
    path: ../packages/module_03

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
